# Generated by Django 2.2.7 on 2020-08-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='let it be empty', null=True, unique=True)),
                ('subject', models.CharField(choices=[('1', 'Physics'), ('2', 'Chemistry'), ('3', 'Programming'), ('4', 'Frontend'), ('5', 'Backend')], default='1', max_length=29)),
                ('total_question', models.PositiveSmallIntegerField(default=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizs',
                'ordering': ['-created'],
            },
        ),
    ]
