# Generated by Django 2.2.7 on 2020-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanalysis',
            name='end',
            field=models.DateTimeField(blank=True),
        ),
    ]
