# Generated by Django 2.2.7 on 2020-08-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20200804_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedstudentanswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.Quiz'),
            preserve_default=False,
        ),
    ]
